gradient_boost:
  hyperparameters:
    learning_rate: 0.1
    max_depth: 3
    min_samples_leaf: 1
    min_samples_split: 2
    n_estimators: 100
    random_state: 42
  model_type: Gradient Boosting
random_forest:
  hyperparameters:
    max_depth: null
    min_samples_leaf: 1
    min_samples_split: 2
    n_estimators: 100
    random_state: 42
  model_type: Random Forest
